### ISSUE TITLE
Complicación guardar datos de vector a variable

### ISSUE THREAD

**Issue by JuanVF606** [PTEC102/ParadigmasDeProgramacion#1]
Hola! 
He estado buscando como guardar los datos en una variable desde un vector para poder trabajarlos por separado  y no logro entender como guardarlos desde un vector , por lo que me encuentro estancado en el inicio del código (literalmente), tengo una idea pero no se si esta correcta, 
            `string xora = splitted[j];  // primer elemento del archivo
            string a = splitted[j + 1];// segundo elemento del archivo`

Espero que me puedan ayudar..

**Comment by Hormash** [comment]
Hola, 

Si, de esa manera vas a guardar cada elemento por cada posición.

Por ejemplo si sabes que el nombre esta en la primera posición, (posición 0) y el apellido en la siguiente, puedes hacer lo siguiente.

`string nombre = splitted[0]; `

`string apellido = splitted[1]; `

Si quieres guardarlo en otro tipo de dato tienes que castearlo.
