### ISSUE TITLE
Duda sobre creacion de Txt y llamamiento de cada clase

### ISSUE THREAD

**Issue by Jgavilnorellana** [PTEC102/ParadigmasDeProgramacion#12]
Buenas, profesor

¿Se debe usar un menú a base de inputs para ir creando de a poco cada TXT o ya deben venir creados/modificados de antes?

**Comment by Hormash** [comment]
¿A que se refiere con un menu?

Su programa debe leer de manera automatica todos los archivos de entrada mencionados en el enunciado.
