### ISSUE TITLE
Error al ejecutar el codigo

### ISSUE THREAD

**Issue by Kr11zz** [PTEC102/ParadigmasDeProgramacion#15]
Hola profe cuando ejecuto el codigo con el g++ clase1.cpp clase2.cpp ......... -o main me tira error el replit con respecto a esto.
![image](https://user-images.githubusercontent.com/101365146/164111514-a353652b-0b18-4970-a99e-462ba32b7dae.png)
me acuerdo que usted habia dicho que utilizemos el #pragma once y se solucionaria? pero en que parte debo implementarlo?. 
gracias.

**Comment by Lebaishompu** [comment]
Tengo el mismo problema pero al ejecutar con g++ main.cpp -o main, si ejecuto  de forma normal el código funciona bien

**Comment by Kr11zz** [comment]
ahí lo logre solucionar @Lebaishompu , era error de los includes , por si te sirve.

**Comment by Lebaishompu** [comment]
Como arreglaste el error de los includes? @Kr11zz
