### ISSUE TITLE
No ejecuta  g++ main.cpp -o main

### ISSUE THREAD

**Issue by Lebaishompu** [PTEC102/ParadigmasDeProgramacion#16]
Hola profe, ahora antes de subir la tarea, tengo problemas con  g++ main.cpp -o main, pero al compilar normalmente no tengo problemas en mi IDE, Zinjal
![image](https://user-images.githubusercontent.com/70242695/164123701-84b3ed17-16c6-401e-bbc4-e6184fbe5997.png)

**Comment by Hormash** [comment]
Segun ese error no no encuentra la carpeta la función main.

Como se llama el archivo que contiene la funcion main? ese archivo es el que debería estar compilando. En caso de tener más archivos o clases .cpp las debe incluir en la linea de compilación. [Si es que no los incluye directamente en el archivo]

**Comment by Lebaishompu** [comment]
main.h, lo llamo en main.cpp. tambien tengo mas archivos y clases .cpp, ya realice la entrega en todo caso
