### ISSUE TITLE
Como compilar clase06/oop en java

### ISSUE THREAD

**Issue by GerardoVCL** [PTEC102/ParadigmasDeProgramacion#19]
Nose si esta plataforma tambien sirve para resolver dudas en general, pero escribo para saber como se compila desde consola toda la carpeta, ya que cuando intento compilar por consola me sale un error que dice "error: cannot find symbol". Estoy ingresando por consola lo siguiente: javac Main.java

**Comment by matgreco** [comment]
Hola Gerardo,

Puedes compilarlo asi:

```
javac -d data *.java
java -cp data EjemploEventos.java
```
