### ISSUE TITLE
Discrepancia entre definición de la clase planificación y diagrama

### ISSUE THREAD

**Issue by Zannisdf** [PTEC102/ParadigmasDeProgramacion#2]
Encontré algunas discrepancias respecto a lo que dice el problema versus lo que muestra el diagrama:

1. El diagrama dice que la clase se llama `Planificacion` mientras que el enunciado dice que se llama `Planificador`. ¿Cuál respetamos? ¿O no hace ninguna diferencia?
2. El enunciado dice que la planificación tiene un `Turno`, pero el diagrama no. ¿Qué respetamos? En caso que se respete el enunciado ¿cómo representamos eso en código? ¿Simplemente le agregamos dos atributos `turnoDía` y `turnoTarde` a la clase planificación? ej.
```c++
class Planificador {
  TurnoDia turnoDia;
  TurnoTarde turnoTarde;
}
```
Aunque esto nuevamente contradice el diagrama, que explica que la clase `Turno` se relaciona con `Planificacion`, no sus subclases, pero si lo hacemos de esta forma:
```c++
class Planificador {
  Turno turno;
}
```
No tenemos cómo saber qué tipo de turno es 🤔

**Comment by Grubsic** [comment]
Se podría usar un tipo enumerado, creamos una clase llamada `TipoTurno`, y declarar algo como:
```
enum season{
    Dia = 0,
    Noche = 1
};
```

Adentro de la clase `Turno`, declarar este atributo.
