### ISSUE TITLE
No matching Items in Maven Repositories

### ISSUE THREAD

**Issue by JuanVF606** [PTEC102/ParadigmasDeProgramacion#20]
Estimados, tengo problema al importar la librería "org.codehaus.jackson.map.ObjectMapper", ya que no lo encuentra en los Repositorios Maven, adjunto imagen. 

![CLASS NOT FOUND IN MAVEN REPOSITORIES](https://user-images.githubusercontent.com/68305071/166965683-56f39bbc-5e7b-44a4-bdef-519e6c367030.png)

Cabe destacar que poseo la ultima versión de NetBeans  IDE 13 y la ultima versión del JDK Java 18. También se ha intentado de encontrar una solución y la cual no a servido de ayuda.
Seria un agrado la respuesta.

**Comment by JuanVF606** [comment]
Gracias por la respuesta.
Pero al seguir los pasos ocurre lo mismo.
![image](https://user-images.githubusercontent.com/68305071/166968531-ef390115-47ae-4a43-88c1-bfab96769061.png)

**Comment by matgreco** [comment]
podrias por favor mostrar que te aparece al hacer click derecho en el proyecto y 

Properties -> Build/Compile -> y ver cual es la Java platform seleccionada?

![2](https://user-images.githubusercontent.com/14565555/166980315-b3e79f22-7978-446d-becf-cb7d27e1fb32.png)


Y tambien ver que aparece al apretar el boton Manage Java Platforms? 
![3](https://user-images.githubusercontent.com/14565555/166980332-a3b343c0-cca5-4a6a-9a01-e41cee2b3190.png)


Si tienes la JDK 17 podrías probarla y ver si funciona. Nos cuentas porfa.

**Comment by Kr11zz** [comment]
Me ocurre el mismo problema 
![Screenshot_435](https://user-images.githubusercontent.com/101365146/167037166-61918f5f-7294-43a1-9864-e3a767a88e18.png)
 
![Screenshot_436](https://user-images.githubusercontent.com/101365146/167043231-1fca9c75-9dfd-4c04-a5ac-4e47ce52c95a.png)
Tengo la Versión JDK15
![Screenshot_437](https://user-images.githubusercontent.com/101365146/167043422-18d26b22-55e1-44e5-ad28-0874557381ac.png)
Por lo tanto debería actualizar al JDK ke envió el profesor?

**Comment by matgreco** [comment]
@Kr11zz podrías probar, en el buscador al agregar una nueva dependencia, solo:

`codehaus.jackson`

**Comment by Kr11zz** [comment]
@matgreco me ocurre el mismo problema del principio, me aparece No matching items

**Comment by JuanVF606** [comment]
@matgreco ya solucione el problema, el proyecto estaba con el compilador JDK 1.8, siendo que debería estar compilando en la versión JDK 18

**Comment by JuanVF606** [comment]
@Kr11zz talvez si actualizas a la ultima versión del JDK ¿?

**Comment by Kr11zz** [comment]
@JuanVF606 como lo actualizaste?

**Comment by JuanVF606** [comment]
@Kr11zz 

1. https://www.oracle.com/java/technologies/downloads/#jdk18-windows -> ingresas al link y seleccionas el .installer
2.  lo instalas como cualquier programa
![image](https://user-images.githubusercontent.com/68305071/167050308-92bff07e-9d72-4e9f-9cd6-e27232321336.png)
pd: Recuerda la ubicación del archivo
3. Una vez instalado te diriges Tools -> Options-> Java-> Maven
4. seleccionas Manage Java Platforms ->add Platform
te deben aparecer pestañas como estas: 
![image](https://user-images.githubusercontent.com/68305071/167050497-33a11238-1293-4b0b-9dd9-014aa87a283e.png)
6.  seleccionas Java Standard Edition -> buscas tu carpeta de java y seleccionas la versión jdk-18.0.1.1
7. Cierras y abres el NETBeans
8. verificas en que compilador esta tu proyecto y lo cambias al JDK 18

**Comment by Kr11zz** [comment]
@JuanVF606 hice todo lo que me dijiste y aun me aparece que No matching items :c

**Comment by dsilvaa8** [comment]
@Kr11zz hice lo mismo y aun me dice no matching items :(, alguien sabe como solucionarlo?

**Comment by matgreco** [comment]
@JuanVF606 @Kr11zz @dsilvaa8 @Hormash 

El problema se debe a que el repositorio central de dependencias no está actualizado.

Primero, corroboremos si está actualizado o no. Para eso, en Netbeans vamos a "Services / Central Repository -> click derecho y properties.
![índice](https://user-images.githubusercontent.com/14565555/167540469-895c98b3-0241-469b-90c9-e94b6bb36bea.jpeg)
Si en la fecha de "Last Indexed" aparece una fecha reciente, no deberíamos tener ningun problema y al buscar "jackson-mapper" al agregar la dependencia debería aparecernos el resultado correctamente. 

Si en la fecha, aparece una fecha inválida (muy antigua, correspondiente a 1969) debemos apretar click derecho sobre Central Repository y apretar "**Update index"**. 

Esto comenzará una actualización del indice de dependencias y podemos ver el avance en la barra de abajo que dice **"Transferring Maven Repository index: Central Repository"**
![Captura de pantalla-20220510000748-1265x739](https://user-images.githubusercontent.com/14565555/167540786-8fbcc5dd-f45b-4645-8c8e-dcce266ff728.png)

En mi caso, el proceso de actualización del repositorio demoró cerca de una hora. Recomiendo no cerrar netbeans hasta que termine de actualizar. Pueden corroborar si fue actualizado ya que la fecha de Last Indexed será la de hoy.

**Comment by MightyRe** [comment]
Nada del post me ha funcionado, no se que más hacer.
Tengo lo siguiente:
![Services](https://user-images.githubusercontent.com/101843380/167960671-fb348ada-27dc-4597-b9cb-38eaee489cf4.png)
![Last Update](https://user-images.githubusercontent.com/101843380/167960710-4f445976-08aa-45ff-bd6d-d77bd4d4124c.png)
![Dependency](https://user-images.githubusercontent.com/101843380/167960733-c71245f1-9ef8-434c-9f05-54538856f3f6.png)
![Properties](https://user-images.githubusercontent.com/101843380/167960741-12f42e53-2676-4bf2-aa90-aafd34af7adf.png)
![Manage](https://user-images.githubusercontent.com/101843380/167960747-4f18e53e-1a9e-4295-b737-4ea83b17294d.png)

**Comment by matgreco** [comment]
En el add dependency, busca solo jackson o jackson-mapper y nos mandas
captura. Yo creo que solo falta el paso de agregar la dependencia de
jackson para el object mapper.

**Comment by MightyRe** [comment]
![image](https://user-images.githubusercontent.com/101843380/168395954-caecaffa-6208-4de1-8164-77223f524ef6.png)

Solo faltaba esto ¯\_(ツ)_/¯

**Comment by matgreco** [comment]
> ![image](https://user-images.githubusercontent.com/101843380/168395954-caecaffa-6208-4de1-8164-77223f524ef6.png)
> 
> Solo faltaba esto ¯_(ツ)_/¯

Perfecto, pero el texto1 lo podrías haber agregado automáticamente haciendo click en "Dependencies" -> Add dependency
