### ISSUE TITLE
Formulario para consultar a la api con POST

### ISSUE THREAD

**Issue by parcecastillo** [PTEC102/ParadigmasDeProgramacion#22]
profesor es necesario que en el la interfaz se agreguen dos campos (usuario y contraseña) para que el usuario escriba los datos y con eso consultamos a la api o el proceso puede ser interno?

![imagen](https://user-images.githubusercontent.com/62722530/169716803-3e8bdd84-ba94-45f6-9e14-f7c00d01c40e.png)

**Comment by Daniel-Sandoval-9** [comment]
profe en que versión de java esta utilizando para HttpClient para invocación de rest

**Comment by matgreco** [comment]
@parcecastillo si, debe tenerla, no debe ser hardcodeada. Sin embargo, mi recomendación es que eso lo termine al final. Una vez que tenga el resto, puede hacer un nuevo formulario el cual se encargue de hacer el login.

**Comment by matgreco** [comment]
@Daniel-Sandoval-9 java 17 o 18. Evite usar java 8 o 1.8. Las instrucciones para instalar java 17 están acá https://github.com/PTEC102/ParadigmasDeProgramacion/tree/main/clase07
