### ISSUE TITLE
Problemas para parsear Json

### ISSUE THREAD

**Issue by fbravoastudillo** [PTEC102/ParadigmasDeProgramacion#24]
Estoy teniendo Problemas para parsear el archivo json.

 String url="https://sjlt81ef5i.execute-api.us-east-1.amazonaws.com/login";
        String jsonString = "{\"username\":\"ptec102\", \"password\":\"202210\"}";
        JsonParser parse=null; 
        ObjectMapper json=(ObjectMapper)parse.parse(jsonString);-----> Aca , no se encuentra metodo parse en JsonParser.
        HttpRequest request= HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type","aplication/json")
                .POST(HttpRequest.BodyPublishers.ofString(jsonString))
                .build();
        HttpClient client = HttpClient.newBuilder()
                .version(HttpClient.Version.HTTP_2)
                .build();

FInalmente al enviar la consulta , devuelve internal error. 
Como se debe parsear correctamente?.

**Comment by Hormash** [comment]
Hola @fbravoastudillo, 

Y ese metodo existe? o que se supone que tiene que hacer?

**Comment by fbravoastudillo** [comment]
Se supone que debiese convertir ese jsonString en formato JSon

**Comment by Hormash** [comment]
y para que se utilizaria en este caso?

**Comment by fbravoastudillo** [comment]
Para pasar el json mediante el post a la api

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hormash** [comment]
Diria que en este caso nose si es necesario ya que esta ingresando un string con el formato JSON.

De todas maneras me llama la atención este String 

`String jsonString = "{"username":"ptec102", "password":"202210"}";`

A usted le funciona esa linea?

**Comment by matgreco** [comment]
@fbravoastudillo Franco, ese codigo que indica hormash no debe funcionar ya que está mal armado el string y además, el json no contiene los caracteres de escape \ . Prueba lo siguiente

```
String jsonString = "{\"usuario\":\"unab\", \"contrasena\":\"pdp\"}";       
        JSONParser parser = new JSONParser();
        try {
            JSONObject json = (JSONObject) parser.parse(jsonString);
            System.out.println(json.get("usuario"));
            System.out.println(json.get("contrasena"));
        } catch (ParseException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
```
Recuerda que debes incluir 
```
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
```
y en la parte de dependencias, agregar org.json.simple

**Comment by fbravoastudillo** [comment]
![Captura de pantalla 2022-05-25 001806](https://user-images.githubusercontent.com/101831268/170178885-c1c1f5bd-3bd1-4331-b919-2c67d8e29738.png)
![Captura de pantalla 2022-05-25 001902](https://user-images.githubusercontent.com/101831268/170178889-677b1f5e-2c14-43b0-b69c-e3824aa2c202.png)

Arregle el codigo , meti las import , importe las dependencias y me dice que faltan las dependencias para JSONPARSE y PARSEEXCEPTION

**Comment by matgreco** [comment]
Pon una captura de la versión de java y el jdk, porfa
