### ISSUE TITLE
No puedo conectar el API

### ISSUE THREAD

**Issue by Elmaldytobastardo** [PTEC102/ParadigmasDeProgramacion#28]
Buenas tardes profesores, he estado horas batallando e investigando mas no puedo encontrar la razón del problema, cuando le paso el json al API de aws, me devuelve el error 500 
![image](https://user-images.githubusercontent.com/62708976/170891767-a7d31a6d-690c-47d3-a9c7-f9a29e0252a4.png)
 siendo que si le entrego el mismo exacto json por Postman, el API me entrega el access_code sin ningún problema 
![image](https://user-images.githubusercontent.com/62708976/170891788-98b4397f-3a7e-4ab0-a3ce-2e85c997e002.png)
¿Alguna idea de cómo solucionarlo? ¿Debo mandar fotos del código de cómo manda el json? He avanzado en todo lo posible dejando este problema para el final, pero ya llegué a una barrera. Gracias de antemano.

**Comment by Hormash** [comment]
Hola @Elmaldytobastardo,

Dado que el servidor se encuetran arriba lo más probable es que tenga un problema en el código al momento de realizar la llamada.

- ¿Esta haciendo la llamada por tipo GET?
- ¿Esta enviando el contedido en el Body?
- ¿El contenido en el body esta indicado en el header como json  ej: `header('Content-Type: application/json')`

**Comment by Elmaldytobastardo** [comment]
Muchas gracias profe, era justamente que me faltó especificar el header.
Saludos.
