### ISSUE TITLE
Error que no se pudo solucionar en la mañana

### ISSUE THREAD

**Issue by choviics** [PTEC102/ParadigmasDeProgramacion#3]
Hola profesor, soy el que la mañana tenia un error que no se como solucionar y dijo que revisaría mi código, ya hice el push de todos los datos.

Error: 
nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: /tmp/ccugofK7.o: in function `Turno_Dia::Turno_Dia()':
main.cpp:(.text+0x3c5): undefined reference to `Turno::Turno()'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: /tmp/ccugofK7.o: in function `Turno_Dia::Turno_Dia(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
main.cpp:(.text+0x3f7): undefined reference to `Turno::Turno()'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: /tmp/ccugofK7.o: in function `Turno_Dia::~Turno_Dia()':
main.cpp:(.text+0x461): undefined reference to `Turno::~Turno()'
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ld: /tmp/ccugofK7.o: in function `Turno_Dia::Turno_Dia(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) [clone .cold]':
main.cpp:(.text.unlikely+0x4): undefined reference to `Turno::~Turno()'
collect2: error: ld returned 1 exit status

**Comment by Hormash** [comment]
Hola @choviics,

¿Actualizaste tu repositorio?

Tienes alguna intuición por donde podria ir el problema?

**Comment by choviics** [comment]
Hola, si ya actualice mi repositorio

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: miércoles, 13 de abril de 2022 16:24
Para: ***@***.***>
CC: CÓRDOVA CASTILLO VICENTE ***@***.***>; ***@***.***>
Asunto: Re: [PTEC102/ParadigmasDeProgramacion] Error que no se pudo solucionar en la mañana (Issue #3)


Hola @choviics<https://github.com/choviics>,

¿Actualizaste tu repositorio?

Tienes alguna intuición por donde podria ir el problema?

**Comment by Hormash** [comment]
Hola @choviics. pille tu error. 

Resulta que estas incluyendo los archivos
```
#include "Usuario.cpp"
#include "Turno_Dia.cpp"
```

Cuando deberías incluir los siguientes archivos.


```
#include "Usuario.h"
#include "Turno_Dia.h"
```

Al menos me compilo con el siguiente comando
`g++ main.cpp Usuario.cpp Turno_Dia.cpp Turno.cpp Turno_Tarde.cpp -o main`
