### ISSUE TITLE
Problema con la lectura de archivos

### ISSUE THREAD

**Issue by Lodred** [PTEC102/ParadigmasDeProgramacion#4]
Tengo el problema de que al leer un archivo utilizando el programa base en main, por ejemplo:

Planificacion, linea 1
1001;2021-03-01;False;0;0;1565514F

El ultimo valor (1565514F) me lo toma con el salto de línea, lo que al compararlo con otro valor idéntico 1565514F no lo reconoce como el mismo valor, quería saber como puedo eliminar el salto de línea para realizar operaciones.

**Comment by matgreco** [comment]
Hola, puedes eliminar los dos ultimos caracteres de la linea (el salto de linea) usando `erase`

Te dejo un ejemplo

```
#include <iostream>
#include <string>

using namespace std;

int main()
{
    string s = "Hola esto es un test";
    s.erase(s.size() - 2); 
    // remueve los ultimos dos caracteres
    // la salida es Hola esto es un te
    cout << s;

    return 0;
}
```
