### ISSUE TITLE
Calcular minutos trabajados

### ISSUE THREAD

**Issue by NinoIturriaga** [PTEC102/ParadigmasDeProgramacion#5]
Buenas tardes profesor, no me queda claro como calcular los minutos trabajados y en donde debería calcularlos, ya que en la clase turno tienen un método para calcular las horas totales menos los minutos de atraso o de anticipo, pero el archivo marcas.txt me entrega horarios distintos.

**Comment by Hormash** [comment]
Hola @NinoIturriaga.
Hola Nino,

Dentro de la clase Planificación hay un método que se llama "TiempoPlanificación" la idea es que esté o un método similar se encargue de actualizar la información de horas trabajadas con respecto a:

- El turno asignado
- La hora de entrada y salida
- Los minutos de atraso o adelanto (dependiendo del tipo turno)

En base a eso, debes cambiar la planificación como asistido si es que hubo marcas y realizar el cálculo de minutos trabajados (para cada día asignado) para agregarlos en el informe.

Saludos.
