### ISSUE TITLE
Problema con replit

### ISSUE THREAD

**Issue by nicolastroncoso** [PTEC102/ParadigmasDeProgramacion#8]
Hola profe, tengo un problema con replit, al tratar de crear el repo me sale que no existe, tengo la cuenta de github con plan pro, no se si me pueda ayudar.
Acepte el link desde la tarea, no se si me estoy saltando un paso o algo al tratar de crear el repositorio.

![image](https://user-images.githubusercontent.com/62604767/163581305-d73a7581-e854-4cd6-821b-c79113da61b2.png)

**Comment by Hormash** [comment]
Hola.

Le recomiendo ir a su repositorio, a la derecha debería decir 'Code' y hacer click, debería aparecer una url para clonar su repositorio.

luego en la consola de replit ejecutar los siguiente sin los '<>'

`git clone <url-repo>`

Lo más problabe es que pida autenticarse en github por lo que debe usar su cuenta de github y el token creado de la misma pagina.

Saludos
