### ISSUE TITLE
¿Quién es el administrador?

### ISSUE THREAD

**Issue by Zannisdf** [PTEC102/ParadigmasDeProgramacion#9]
En el enunciado se explica que sólo un `Administrador` puede agregar planificaciones a los usuarios, pero en ninguna parte se explica quién corresponde a un administrador y el archivo de entrada de usuarios tampoco lo establece. ¿Asumimos que el primer usuario siempre va a ser admin?

**Comment by Hormash** [comment]
Hola @Zannisdf,

El Administrador debe existir en tu programa. Debe ser un objeto que se instancia y asigna a los usuarios sus planificaciones correspondientes.

**Comment by rdelahozr** [comment]
Tengo la misma duda.
No entiendo cual es la idea de `Administrador`, si la planificación,  supongo, esta definida en el archivo Planificación.txt

**Comment by Hormash** [comment]
> Tengo la misma duda. No entiendo cual es la idea de `Administrador`, si la planificación, supongo, esta definida en el archivo Planificación.txt

@rdelahozr eso es correcto está definida, pero eso no quiere decir que en código o en el programa esté asociada a la cada usuario. El que se encarga de hacer eso es decir ver qué planificaciones le corresponden a cada usuario debe ser un método de la clase administrador.

Este método recibe un usuario y una lista de planificaciones y las asigna al usuario. Cuando digo asignar me refiero a lo siguiente

`obj_usuario.planificaciones = lista_de_planificaciones_solo_de_este_usuario`
